# Change these first
owner: sebascontre # Your GitHub organization or username, where this repository lives
repo: upptime-satellite # The name of this repository

sites:
  - name: Satellite Sitio Web
    url: https://satellite.moe
  - name: Satellite 24/7
    url: https://twitch.tv/satellitemoe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.satellite.moe
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Satellite Uptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://satellite.moe
    - title: 24/7
      href: https://twitch.tv/satellitemoe

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
